apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.storage.class }}
  storageClassName: {{ .Values.storage.class }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
